name: Closed issue labels

on:
  issues:
    types: closed

permissions:
  contents: read

jobs:
  remove_triage_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: remove label for closed issue
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        if: ${{ github.event.issue.state_reason == 'not_planned' }}
        with:
          labels: to-triage

  add_triage_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: add label for issue without milestone
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
        if: ${{ github.event.issue.state_reason == 'completed' && github.event.issue.milestone == null }}
        with:
          labels: to-triage
