name: Opened issue labels

on:
  issues:
    types: opened

permissions:
  contents: read

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: add label for issue without labels
        uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1.1.3
        if: ${{ github.event.issue.labels[0] == null }}
        with:
          labels: to-triage
