name: 'Requeue stale team-triage issues'
on:
  schedule:
    # Execute every day
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  requeue:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
          operations-per-run: 30
          only-labels: ':wave: team-triage'

          days-before-issue-stale: 14

          stale-issue-label: to-triage
          stale-issue-message: ""
          days-before-issue-close: -1

          days-before-pr-stale: -1
          days-before-pr-close: -1
